import test from 'node:test';import assert from 'node:assert/strict';
import {SyncEngine} from '../src/engine';import {makeBlock,managed,safeFolder,sha} from '../src/document';import {defaults,emptyState,SyncProblem,type Host,type Server,type Checkin,type Task} from '../src/types';
async function fixture(){const data=new Uint8Array([255,216,255,217]).buffer;const source={source_ref:'tasknotes:source-generation',connection_id:'connection',path:'Tasks/读书.md',snapshot:{status:'open',dateCreated:'2026-10-07T00:00:00Z',title:'读书'}};const item:Checkin={cursor:1,record_id:'record',instance_id:'instance',task_id:'task',revision:1,current_revision:1,logical_status:'started',paca_status_id:'progress',kind:'start',submitted_at:'2026-10-07T01:00:00Z',note:'阅读第五章',media_id:'photo',media_sha256:await sha(data),media_bytes:4,media_mime:'image/jpeg',media_expired:false,source};const state=emptyState();const settings={...defaults,attachments:'PushGo附件',pacaStates:{open:'todo','in-progress':'progress',done:'done'}};const notes=new Map([['Tasks/读书.md','---\nstatus: open\n---\n原始正文\n']]);const tasks=new Map<string,Task>([[source.path,{path:source.path,title:'读书',status:'open',dateCreated:source.snapshot.dateCreated}]]);const media=new Map<string,ArrayBuffer>();let downloads=0,pulls=0,saves=0,statusWrites=0,failAck=false;const prepared=new Map<string,{id:string;status:string;path:string;hash:string;base:string}>();const host:Host={task:async p=>tasks.get(p)??null,tasks:async()=>[...tasks.values()],taskFolder:()=> 'Tasks',read:async p=>{assert(notes.has(p));return notes.get(p)!},process:async(p,fn)=>{notes.set(p,fn(notes.get(p)!))},setStatus:async(p,status)=>{tasks.get(p)!.status=status;statusWrites++},exists:p=>notes.has(p)||media.has(p),binary:async p=>media.get(p)!,writeBinary:async(p,d)=>{assert(!media.has(p));media.set(p,d)},mkdir:async()=>{},save:async()=>{saves++}};const receipts=new Map<string,{id:string;status:string;path:string;hash:string;base:string}>();const server:Server={changes:async after=>{pulls++;return {items:after<item.cursor?[structuredClone(item)]:[],next_cursor:Math.max(after,item.cursor),has_more:false}},source:async()=>source,media:async()=>{downloads++;return data},receipt:async(_i,op,status,base,path,hash)=>{const next={id:op,status,path,hash,base};const prior=prepared.get(op);if(prior)assert.deepEqual(prior,next);else prepared.set(op,next);receipts.set(op,next);return {id:op}},ack:async(id,status,path,hash)=>{const receipt=receipts.get(id)!;assert.equal(receipt.status,status);assert.equal(receipt.path,path);assert.equal(receipt.hash,hash);if(failAck&&id.startsWith('body:')){failAck=false;throw new Error('response lost')}},conflict:async()=>({id:'conflict'}),resolve:async(_id,_i,keep)=>{if(keep==='local'){item.cursor++;item.current_revision++;item.revision++;item.logical_status='mapped';item.paca_status_id='todo'}}};const engine=new SyncEngine(host,server,settings,state);return {engine,host,server,state,settings,item,notes,tasks,media,counts:()=>({downloads,pulls,saves,statusWrites}),failAck:()=>{failAck=true}}}
test('manual and automatic pulls share a run, preserve text, deduplicate media and records',async()=>{const f=await fixture();await Promise.all([f.engine.run(),f.engine.run()]);assert.equal(f.counts().pulls,1);assert.equal(f.counts().downloads,1);assert.equal(f.tasks.get(f.item.source.path)!.status,'in-progress');const text=f.notes.get(f.item.source.path)!;assert(text.includes('原始正文'));assert(text.includes('开始打卡'));assert(text.includes('![[PushGo附件/photo.jpg]]'));await f.engine.run();assert.equal(f.counts().downloads,1);assert.equal(f.notes.get(f.item.source.path),text);assert.equal(f.counts().statusWrites,1)});
test('changed local state pauses state write but retains photos and records',async()=>{const f=await fixture();f.tasks.get(f.item.source.path)!.status='cancelled';await f.engine.run();assert.equal(f.tasks.get(f.item.source.path)!.status,'cancelled');assert.equal(f.media.size,1);assert(f.notes.get(f.item.source.path)!.includes('开始打卡'));assert.equal(f.state.links[f.item.source.source_ref].conflict,'conflict');assert(f.state.pending.record.problem?.includes('状态'));await f.engine.choose(f.item.source.source_ref,'server');assert.equal(f.tasks.get(f.item.source.path)!.status,'in-progress')});
test('response loss after body write resumes receipts without replacing photos',async()=>{const f=await fixture();await f.engine.run();f.item.cursor=2;f.item.revision=2;f.item.current_revision=2;f.item.kind='due';f.item.logical_status='completed';f.item.record_id='record-end';f.failAck();await f.engine.run();assert.equal(f.tasks.get(f.item.source.path)!.status,'done');assert(!f.state.pending['record-end'].done);const restored=JSON.parse(JSON.stringify(f.state)) as typeof f.state;const fresh=new SyncEngine(f.host,f.server,f.settings,restored);await fresh.run();assert(restored.pending['record-end'].done);assert.equal(f.counts().downloads,1);assert.equal(f.counts().statusWrites,2)});
test('deleted note is not recreated; managed edits are not overwritten',async()=>{const f=await fixture();await f.engine.run();f.item.cursor=2;f.item.revision=2;f.item.current_revision=2;f.item.record_id='new';const original=f.notes.get(f.item.source.path)!;f.notes.set(f.item.source.path,original.replace('阅读第五章','我的修改'));await f.engine.run();assert(f.notes.get(f.item.source.path)!.includes('我的修改'));assert(f.state.pending.new.problem?.includes('区块'));f.tasks.delete(f.item.source.path);f.notes.delete(f.item.source.path);await f.engine.run();assert(!f.notes.has(f.item.source.path));assert(f.state.pending.new.problem?.includes('未找到'))});
test('dateCreated distinguishes a new file generation with the same path',async()=>{const f=await fixture();f.tasks.get(f.item.source.path)!.dateCreated='2026-10-07T02:00:00Z';await f.engine.run();assert.equal(f.counts().statusWrites,0);assert(f.state.pending.record.problem?.includes('关联'))});
test('date-only old record can sync photos without overwriting a newer state',async()=>{const f=await fixture();f.item.current_revision=2;await f.engine.run();assert.equal(f.counts().statusWrites,0);assert.equal(f.media.size,1)});
test('attachment folder excludes task folder, nested task paths, hidden traversal',()=>{for(const folder of ['Tasks','tasks/images','../照片','.obsidian/x','照片/../x'])assert.throws(()=>safeFolder(folder,'Tasks'),SyncProblem);assert.equal(safeFolder('PushGo附件/','Tasks'),'PushGo附件');assert.throws(()=>safeFolder('照片',''),SyncProblem)});
test('malformed or duplicate managed sections require human repair',()=>{assert.throws(()=>managed('<!-- paca-checkin:start -->'),SyncProblem);assert(makeBlock([]).includes('拍照打卡'))});

test('invalid media names and checksums never create attachment paths',async()=>{const f=await fixture();f.item.media_id='../bad';await f.engine.run();assert.equal(f.counts().downloads,0);assert.equal(f.media.size,0);assert(f.state.pending.record.problem?.includes('照片信息'))});

test('missing source does not block photos or another task',async()=>{const f=await fixture();f.server.source=async()=>({...f.item.source,source_state:'unlinked'});await f.engine.run();assert.equal(f.media.size,1);assert.equal(f.counts().statusWrites,0);assert.equal(f.state.pending.record.errorCode,'source_missing');});
test('local completion is rechecked when its photo was removed',async()=>{const f=await fixture();await f.engine.run();f.media.clear();await f.engine.run();assert.equal(f.counts().downloads,2);assert(f.state.pending.record.done);});
test('history association writes records and photos without changing task state',async()=>{const f=await fixture();f.tasks.get(f.item.source.path)!.status='done';f.server.deliveries=async after=>({items:after===0?[{record_id:'record',policy:'active',revision:2,reason:'user_recovery',historical_path:f.item.source.path,historical_created:f.item.source.snapshot.dateCreated!,state:'pending',attempts:0,error_code:'',media_verified:false,record_written:false,status_verified:false}]:[],next_cursor:1,has_more:false});f.server.source=async()=>{throw new SyncProblem('missing','来源不存在')};await f.engine.run();assert(f.state.pending.record.done);assert.equal(f.counts().statusWrites,0);assert(f.notes.get(f.item.source.path)!.includes('开始打卡'));});
test('shared ignored policy prevents download but preserves the pending record',async()=>{const f=await fixture();f.server.deliveries=async()=>({items:[{record_id:'record',policy:'ignored',revision:2,reason:'user_ignored',historical_path:'',historical_created:'',state:'pending',attempts:0,error_code:'',media_verified:false,record_written:false,status_verified:false}],next_cursor:1,has_more:false});await f.engine.run();assert.equal(f.counts().downloads,0);assert.equal(f.state.pending.record.item.record_id,'record');});
test('retry exhaustion and the retry deadline are enforced locally',async()=>{const f=await fixture();f.server.deliveries=async()=>({items:[{record_id:'record',policy:'active',revision:1,reason:'',historical_path:'',historical_created:'',state:'needs_action',attempts:10,error_code:'photo',media_verified:false,record_written:false,status_verified:false}],next_cursor:1,has_more:false});await f.engine.run();await f.engine.run();assert.equal(f.counts().downloads,0);});
test('a lost delivery response repeats the persisted operation',async()=>{const f=await fixture();let failed=true;const ids:string[]=[];f.server.deliveries=async after=>({items:after===0?[{record_id:'record',policy:'active',revision:1,reason:'',historical_path:'',historical_created:'',state:'pending',attempts:0,error_code:'',media_verified:false,record_written:false,status_verified:false}]:[],next_cursor:1,has_more:false});f.server.report=async body=>{ids.push(body.op_id);if(failed){failed=false;throw new SyncProblem('unavailable','服务暂不可用')}return {state:body.stage==='confirmed'?'confirmed':'pending'}};await f.engine.run();await f.engine.run();assert.equal(ids[0],ids[1]);assert(f.state.pending.record.done);});

test('needs-association records can save a photo without writing a task',async()=>{const f=await fixture();f.server.deliveries=async()=>({items:[{record_id:'record',policy:'active',revision:1,reason:'source_missing',historical_path:'',historical_created:'',state:'needs_action',attempts:0,error_code:'source_missing',media_verified:false,record_written:false,status_verified:false}],next_cursor:1,has_more:false});f.server.report=async()=>({state:'needs_action'});await f.engine.run();assert.equal(f.media.size,1);assert.equal(f.counts().statusWrites,0);assert(!f.state.pending.record.done);});
test('a failed photo does not block another card of the same task',async()=>{const f=await fixture();const good=structuredClone(f.item);good.cursor=2;good.record_id='good';good.media_id='good-photo';f.item.media_id='bad-photo';f.server.changes=async after=>({items:after===0?[structuredClone(f.item),good]:[],next_cursor:2,has_more:false});const media=f.server.media;f.server.media=async id=>{if(id==='bad-photo')throw new SyncProblem('transfer_unavailable','照片传输中断');return media(id)};await f.engine.run();assert(f.state.pending.good.done);assert(!f.state.pending.record.done);assert(f.notes.get(f.item.source.path)!.includes('good-photo.jpg'));});
test('an ignored already-written record remains in the note when another card arrives',async()=>{const f=await fixture();await f.engine.run();const first=f.item.record_id;f.item.cursor=2;f.item.record_id='new-card';f.item.revision=2;f.item.current_revision=2;f.item.kind='due';f.item.logical_status='completed';f.state.deliveries={[first]:{record_id:first,policy:'ignored',revision:2,reason:'user_ignored',historical_path:'',historical_created:'',state:'pending',attempts:0,error_code:'',media_verified:true,record_written:true,status_verified:true}};await f.engine.run();const text=f.notes.get(f.item.source.path)!;assert(text.includes('开始打卡')&&text.includes('结束打卡'));});
