import test from 'node:test';
import assert from 'node:assert/strict';
import {TaskSyncEngine,sharedBody,replaceSharedBody} from '../src/task-sync-engine';
import {emptyTaskState,type SyncedTask,type TaskSnapshot,type TaskChange,type TaskSyncHost,type TaskSyncServer,type TaskOperation} from '../src/task-sync-types';
import {SyncProblem} from '../src/types';

function fixture(){
 const id='11111111-1111-4111-8111-111111111111';const state=emptyTaskState();const tasks=new Map<string,SyncedTask>();const item:TaskChange={cursor:1,sync_id:id,task_id:'core-task',revision:1,kind:'task',deleted:false,path:'',note_created:'',source_ref:'sync:'+id,snapshot:{title:'Paca 创建任务',status:'open',priority:'normal',details:'普通内容',scheduled:'2026-10-09T09:00:00',due:'2026-10-09T10:00:00',archived:false,tags:['学习']}};
 let created=0,written=0,removed=0,pulls=0,saves=0,lostCreate=false;const submitted:TaskOperation[]=[];const acknowledgments:TaskSnapshot[]=[];let binding={state:'unbound',path:'',note_created:''};
 const host:TaskSyncHost={task:async path=>tasks.get(path)??null,find:async marker=>[...tasks.values()].find(t=>t.marker===marker)??null,create:async(snapshot,marker)=>{created++;const task={...snapshot,path:'Tasks/来自 Paca.md',dateCreated:'2026-10-08T00:00:00Z',marker};tasks.set(task.path,task);if(lostCreate){lostCreate=false;throw Error('created note, result lost')}return task},update:async(path,patch)=>{written++;const task=tasks.get(path)!;Object.assign(task,patch);return task},delete:async path=>{removed++;tasks.delete(path)},snapshot:async task=>{const result:Record<string,unknown>={...task};delete result.path;delete result.dateCreated;delete result.marker;return result as TaskSnapshot},save:async()=>{saves++},bound:()=>{}};
 const server:TaskSyncServer={info:async()=>({mode:'enabled'}),changes:async cursor=>{pulls++;return {items:cursor<item.cursor?[structuredClone(item)]:[],next_cursor:Math.max(item.cursor,cursor),has_more:false,mode:'enabled'}},binding:async(_id,action,path,birth)=>{if(binding.state==='bound')return binding;if(action==='claim'){binding.state='creating';return{state:'claimed'}}binding={state:'bound',path:path!,note_created:birth!};return binding},submit:async op=>{submitted.push(structuredClone(op));return{state:'pending'}},operation:async()=>({state:'pending'}),receipt:async(_item,op)=>({id:op}),ack:async(_receipt,snapshot)=>{acknowledgments.push(structuredClone(snapshot))},lookup:async()=>{throw new SyncProblem('missing','not imported')},conflicts:async()=>({items:[]}),resolve:async()=>{}};
 return {id,state,tasks,item,host,server,engine:new TaskSyncEngine(host,server,state),submitted,acknowledgments,counts:()=>({created,written,removed,pulls,saves}),loseCreate:()=>{lostCreate=true}};
}

test('Paca task creates a note without check-in; manual and auto share one run',async()=>{const f=fixture();await Promise.all([f.engine.run(),f.engine.run()]);assert.equal(f.counts().created,1);assert.equal(f.counts().pulls,1);assert.equal(f.state.links[f.id].revision,1);assert.equal(f.tasks.size,1);await f.engine.run();assert.equal(f.counts().created,1)});
test('result lost after note creation is recovered through marker before creating again',async()=>{const f=fixture();f.loseCreate();await f.engine.run();assert.equal(f.tasks.size,1);assert.equal(f.state.links[f.id].intent,true);assert(f.state.problems[f.id]);await f.engine.run();assert.equal(f.counts().created,1);assert.equal(f.state.links[f.id].intent,false);assert.deepEqual(f.state.problems,{})});
test('missing note is visible and never silently recreated',async()=>{const f=fixture();await f.engine.run();f.tasks.clear();f.item.cursor++;f.item.revision++;f.item.snapshot.title='改名';await f.engine.run();assert.equal(f.counts().created,1);assert.match(f.state.problems[f.id],/缺失/) });
test('server changes another field; hand-written Markdown time remains local',async()=>{const f=fixture();await f.engine.run();const note=[...f.tasks.values()][0];note.scheduled='2026-11-01T12:00:00';f.item.cursor++;f.item.revision++;f.item.snapshot.priority='high';await f.engine.run();assert.equal(note.scheduled,'2026-11-01T12:00:00');assert.equal(note.priority,'high');assert.equal(f.state.links[f.id].base.scheduled,'2026-10-09T09:00:00');assert.equal(f.acknowledgments.at(-1)!.scheduled,'2026-11-01T12:00:00','actual write was fabricated in receipt')});
test('UI priority mutation queues exactly that field after a manual date edit',async()=>{const f=fixture();await f.engine.run();const note=[...f.tasks.values()][0];const before={...note,scheduled:'2026-11-01T12:00:00'};const after={...before,priority:'high'};await f.engine.capture('update',before,after,{priority:{before:'normal',after:'high'}});const operation=Object.values(f.state.operations)[0];assert.deepEqual(operation.body.changes,{priority:'high'});assert.equal(operation.body.base.scheduled,'2026-10-09T09:00:00')});
test('same field and delete-vs-local-edit conflicts preserve note until explicit decision',async()=>{const f=fixture();await f.engine.run();const note=[...f.tasks.values()][0];note.title='本地修改';f.item.cursor++;f.item.revision++;f.item.snapshot.title='服务器修改';await f.engine.run();assert.equal(note.title,'本地修改');assert.match(f.state.problems[f.id],/修改/);f.item.cursor++;f.item.revision++;f.item.deleted=true;await f.engine.run();assert.equal(f.counts().removed,0);await f.engine.choose(f.id,'server');await f.engine.run();assert.equal(f.counts().removed,1)});
test('a second client waits for the existing binding and does not create duplicates',async()=>{const f=fixture();f.server.binding=async()=>({state:'bound',path:'Tasks/另一个设备.md',note_created:'2026-10-08T00:00:00Z'});await f.engine.run();assert.equal(f.counts().created,0);assert.match(f.state.problems[f.id],/另一设备/)});
test('unsupported rich text is visible and never overwritten with empty content',async()=>{const f=fixture();f.item.warnings=['原始内容暂不支持'];await f.engine.run();assert.equal(f.tasks.size,0);assert.match(f.state.problems[f.id],/原始内容/)});
test('ordinary content excludes check-in images and preserves private blocks on replacement',()=>{const input='<!-- paca-sync-id:11111111-1111-4111-8111-111111111111 -->\n<!-- paca-task-content:start -->\n旧内容\n<!-- paca-task-content:end -->\n私人笔记\n<!-- paca-checkin:start -->\n![[PushGo附件/a.jpg]]\n<!-- paca-checkin:end -->';assert.equal(sharedBody(input),'旧内容');const updated=replaceSharedBody(input,'新内容','11111111-1111-4111-8111-111111111111');assert(updated.includes('私人笔记'));assert(updated.includes('![[PushGo附件/a.jpg]]'));assert.equal(sharedBody(updated),'新内容')});

