import {SyncProblem,type Pending} from './types';
const start='<!-- paca-checkin:start -->', end='<!-- paca-checkin:end -->';
export async function sha(data:string|ArrayBuffer):Promise<string>{const bytes=typeof data==='string'?new TextEncoder().encode(data):new Uint8Array(data);return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('')}
export function parts(text:string):{front:string;body:string}{const match=/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/.exec(text);return {front:match?.[0]??'',body:match?text.slice(match[0].length):text}}
export function managed(text:string):string|null{const body=parts(text).body;const a=body.indexOf(start),b=body.indexOf(end);if(a<0&&b<0)return null;if(a<0||b<a||body.indexOf(start,a+start.length)>=0||body.indexOf(end,b+end.length)>=0)throw new SyncProblem('block','打卡区块被修改，请检查后重新同步。');return body.slice(a,b+end.length)}
export function replaceBlock(text:string,block:string):string{const old=managed(text);if(old)return text.replace(old,block);return text+(text.endsWith('\n')?'':'\n')+'\n'+block+'\n'}
function plain(value:string):string{return value.replace(/[[\]()*_`!<>#|\\]/g,'\\$&').replace(/\r?\n/g,'  \n')}
export function makeBlock(records:Pending[]):string {const rows=[start,'## 拍照打卡',''];for(const p of [...records].sort((a,b)=>a.item.submitted_at.localeCompare(b.item.submitted_at))){const c=p.item;const time=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',dateStyle:'medium',timeStyle:'medium',hour12:false}).format(new Date(c.submitted_at));rows.push(`### ${c.kind==='start'?'开始打卡':'结束打卡'}`,`- 时间：${time}`,`- 状态：${c.logical_status==='completed'?'已完成':c.logical_status==='started'?'进行中':'已同步'}`);if(c.note)rows.push(`- 备注：${plain(c.note)}`);if(p.expired)rows.push('- 照片：已超过保存期限');else if(p.photo)rows.push(`![[${p.photo}]]`);else rows.push('- 照片：等待下载');rows.push('');}rows.push(end);return rows.join('\n')}
export function safeFolder(folder:string,tasks:string):string{const value=folder.trim().replace(/^\/+|\/+$/g,'');const task=tasks.trim().replace(/^\/+|\/+$/g,'');if(!value||!task||value.split('/').some(p=>!p||p==='.'||p==='..'||p.startsWith('.'))||/[\\<>:"|?*\x00-\x1f[\]#^]/.test(value)||value.toLocaleLowerCase()===task.toLocaleLowerCase()||value.toLocaleLowerCase().startsWith(task.toLocaleLowerCase()+'/'))throw new SyncProblem('folder','请选择任务目录以外的独立附件目录。');return value}
export function targetStatus(item:{logical_status:string;paca_status_id:string},settings:{started:string;completed:string;pacaStates:Record<string,string>}):string{if(item.logical_status==='started')return settings.started;if(item.logical_status==='completed')return settings.completed;const found=Object.entries(settings.pacaStates).find(([,id])=>id===item.paca_status_id);if(!found)throw new SyncProblem('mapping','请配置这次打卡对应的任务状态。');return found[0]}
