import {type Host,type Server,type Settings,type State,type Pending,type Link,type Source,type Task,type DeliveryReport,SyncProblem} from './types';
import {sha,parts,managed,replaceBlock,makeBlock,safeFolder,targetStatus} from './document';
export class SyncEngine {
 private running:Promise<void>|null=null;
 constructor(readonly host:Host,readonly server:Server,readonly settings:Settings,readonly state:State){}
 run():Promise<void>{if(this.running)return this.running;this.running=this.sync().finally(()=>{this.running=null});return this.running}
 private async refreshDeliveries():Promise<void>{if(!this.server.deliveries)return;this.state.deliveries??={};for(let page=0;page<50;page++){const feed=await this.server.deliveries(this.state.deliveryCursor??0);if(feed.next_cursor<(this.state.deliveryCursor??0))throw new SyncProblem('feed','同步进度异常，请稍后重试。');for(const item of feed.items){const prior=this.state.deliveries[item.record_id];this.state.deliveries[item.record_id]=item;const p=this.state.pending[item.record_id];if(item.policy==='purging'||item.policy==='purged'){if(p?.recordWritten){this.state.deliveries[item.record_id]={...item,historical_path:prior?.historical_path??item.historical_path,historical_created:prior?.historical_created??item.historical_created};p.done=true;p.problem=undefined;p.errorCode=undefined;p.report=undefined;}else{if(p)delete this.state.media[p.item.media_id];delete this.state.pending[item.record_id];}continue;}if(p&&prior&&item.revision!==prior.revision){p.done=false;p.problem=undefined;p.errorCode=undefined;p.report=undefined;}}this.state.deliveryCursor=feed.next_cursor;await this.host.save();if(!feed.has_more)break;}}
 private async report(p:Pending,stage:DeliveryReport['stage'],code=''):Promise<void>{const d=this.state.deliveries?.[p.item.record_id];if(!this.server.report||!d||d.policy!=='active')return;if(!p.report){p.report={record_id:p.item.record_id,op_id:crypto.randomUUID(),base_revision:d.revision,stage,error_code:code,media_sha256:p.item.media_sha256,media_verified:!!p.photo||!!p.expired,record_written:!!p.recordWritten,status_verified:!!p.statusVerified};await this.host.save();}try{const result=await this.server.report(p.report);Object.assign(d,result);p.report=undefined;await this.host.save();}catch(e){if(e instanceof SyncProblem&&e.code==='revision'){p.report=undefined;await this.host.save();await this.refreshDeliveries();return;}throw e;}}
 private groupKey(p:Pending):string{const d=this.state.deliveries?.[p.item.record_id];return p.item.source.source_ref+(d?.historical_path?'|historical:'+d.historical_path+'|'+d.historical_created:'')}
 private eligible(p:Pending):boolean{const d=this.state.deliveries?.[p.item.record_id];return !d||(d.policy==='active'&&d.state!=='needs_action'&&(d.state!=='retry_wait'||!d.next_attempt||Date.parse(d.next_attempt)<=Date.now()));}
 private async sync():Promise<void>{safeFolder(this.settings.attachments,this.host.taskFolder());let pages=0;do{const feed=await this.server.changes(this.state.cursor);if(feed.next_cursor<this.state.cursor)throw new SyncProblem('feed','同步进度异常，请重新连接。');for(const item of feed.items){if(!item.source?.source_ref||!item.record_id)continue;const policy=this.state.deliveries?.[item.record_id]?.policy;if(policy==='purging'||policy==='purged')continue;const prior=this.state.pending[item.record_id];if(!prior||item.cursor>prior.item.cursor)this.state.pending[item.record_id]={...prior,item,done:false};}this.state.cursor=feed.next_cursor;await this.host.save();if(!feed.has_more)break;}while(++pages<50);
 await this.refreshDeliveries();for(const p of Object.values(this.state.pending)){const policy=this.state.deliveries?.[p.item.record_id]?.policy;if(policy==='purging'||policy==='purged')continue;if(p.report){try{await this.report(p,p.report.stage)}catch{continue;}}if(p.done){const link=this.state.links[this.groupKey(p)];const task=link?await this.host.task(link.path):null;const photoMissing=p.photo&&(!this.host.exists(p.photo)||await sha(await this.host.binary(p.photo))!==p.item.media_sha256);const noteMissing=link&&(!task||(link.created&&task.dateCreated!==link.created));let bodyMissing=false;if(link&&task&&link.blockHash){try{const block=managed(await this.host.read(link.path));bodyMissing=!block||await sha(block)!==link.blockHash;}catch{bodyMissing=true;}}if(photoMissing||noteMissing||bodyMissing){p.done=false;if(photoMissing)p.photo=undefined;p.recordWritten=false;p.statusVerified=false;}}}
 const groups=new Map<string,Pending[]>();for(const p of Object.values(this.state.pending)){const d=this.state.deliveries?.[p.item.record_id];if(d&&d.policy!=='active')continue;if(p.report)continue;const needsPhotos=d?.state==='needs_action'&&['source_missing','missing','block','status','mapping'].includes(d.error_code)&&!p.photo&&!p.expired;if(!this.eligible(p)&&!needsPhotos)continue;const key=this.groupKey(p);groups.set(key,[...(groups.get(key)??[]),p]);}
 for(const [ref,rows] of groups){if(rows.every(p=>p.done))continue;const ready:Pending[]=[];for(const p of rows){if(p.done){ready.push(p);continue;}try{await this.photo(p);await this.report(p,'progress');if(this.eligible(p))ready.push(p);}catch(e){await this.failed(p,e);}}if(!ready.length||ready.every(p=>p.done))continue;
 try{await this.apply(ref,ready);for(const p of ready){p.recordWritten=true;p.problem=undefined;p.errorCode=undefined;await this.report(p,'confirmed');p.done=this.state.deliveries?.[p.item.record_id]?.policy!=='active'||this.state.deliveries?.[p.item.record_id]?.state==='confirmed'||!this.server.report;}await this.host.save()}catch(e){for(const p of ready.filter(p=>!p.done)){await this.failed(p,e);}await this.host.save();}}
 }
 private async failed(p:Pending,e:unknown):Promise<void>{p.done=false;p.problem=e instanceof SyncProblem?e.userMessage:'暂时无法同步，将稍后重试。';p.errorCode=e instanceof SyncProblem?e.code:'unavailable';await this.host.save();try{await this.report(p,'failed',p.errorCode)}catch{/* Persist the exact report for the next connection. */}}
 private async photo(p:Pending):Promise<void>{if(!/^[a-zA-Z0-9-]{1,80}$/.test(p.item.media_id)||!(/^[a-f0-9]{64}$/.test(p.item.media_sha256))||p.item.media_bytes<1||p.item.media_bytes>10485760||p.item.media_mime!=='image/jpeg')throw new SyncProblem('photo','照片信息无效，请重新同步。');if(p.expired)return;if(p.photo&&this.host.exists(p.photo)&&await sha(await this.host.binary(p.photo))===p.item.media_sha256)return;p.photo=undefined;if(p.item.media_expired){p.expired=true;return;}const folder=safeFolder(this.settings.attachments,this.host.taskFolder());const cached=this.state.media[p.item.media_id];if(cached&&cached.sha===p.item.media_sha256&&this.host.exists(cached.path)&&await sha(await this.host.binary(cached.path))===cached.sha){p.photo=cached.path;return;}let data:ArrayBuffer;try{data=await this.server.media(p.item.media_id)}catch(e){if(e instanceof SyncProblem&&e.code==='expired'){p.expired=true;return;}throw e;}if(data.byteLength!==p.item.media_bytes||await sha(data)!==p.item.media_sha256)throw new SyncProblem('photo','照片校验失败，请重新下载。');const path=`${folder}/${p.item.media_id}.jpg`;await this.host.mkdir(folder);if(this.host.exists(path)&&await sha(await this.host.binary(path))!==p.item.media_sha256)throw new SyncProblem('photo','同名照片已被修改，请保留后更换附件目录。');if(!this.host.exists(path))await this.host.writeBinary(path,data);p.photo=path;this.state.media[p.item.media_id]={path,sha:p.item.media_sha256};await this.host.save();}
 async action(record:string,action:'retry'|'ignore'|'restore'|'associate',task?:Task):Promise<void>{const p=this.state.pending[record],d=this.state.deliveries?.[record];if(!p||!d||!this.server.action)throw new SyncProblem('unavailable','请先同步记录后再处理。');if(action==='associate'&&(!task?.path||!task.dateCreated))throw new SyncProblem('missing','请选择具有创建信息的任务笔记。');await this.server.action({connection_id:p.item.source.connection_id,record_id:record,op_id:crypto.randomUUID(),action,base_revision:d.revision,...(task?{path:task.path,note_created:task.dateCreated}:{})});await this.refreshDeliveries();await this.host.save();await this.run();}
 private async locate(source:Source,link?:Link):Promise<Task>{if(link){const task=await this.host.task(link.path);if(task&&(!link.created||task.dateCreated===link.created))return task;throw new SyncProblem('missing','任务笔记未找到，请重新关联。');}let task=await this.host.task(source.path);if(!task){for(const path of source.aliases??[]){task=await this.host.task(path);if(task)break;}}const created=source.snapshot.dateCreated;if(!task||!created||task.dateCreated!==created)throw new SyncProblem('missing','任务尚未关联，请在同步设置中选择对应笔记。');return task;}
 private async apply(ref:string,rows:Pending[]):Promise<void>{const latest=[...rows].sort((a,b)=>b.item.cursor-a.item.cursor)[0].item;let source=latest.source;const policy=this.state.deliveries?.[latest.record_id];const historical=!!policy?.historical_path;
 if(historical)source={...source,path:policy!.historical_path,aliases:[],snapshot:{...source.snapshot,dateCreated:policy!.historical_created},source_state:'unlinked'};
 else {const fresh=await this.server.source(latest.task_id);if(fresh.source_ref!==latest.source.source_ref)throw new SyncProblem('source_missing','任务来源需要核对，请重新关联笔记。');source=fresh;if(source.source_state==='deleted'||source.source_state==='unlinked')throw new SyncProblem('source_missing','历史任务来源需要核对，可重新关联笔记或忽略此同步项。');}
 let link=this.state.links[ref];const task=await this.locate(source,link);if(!link){link={path:task.path,created:task.dateCreated??source.snapshot.dateCreated,status:latest.source.snapshot.status,revision:0};this.state.links[ref]=link;await this.host.save();}

 const text=await this.host.read(link.path);const oldBlock=managed(text);if(link.blockHash&&(!oldBlock||(await sha(oldBlock)!==link.blockHash && !(link.pendingBody&&await sha(parts(text).body.trim())===link.pendingBody))))throw new SyncProblem('block','打卡区块已被编辑或删除，请保留修改后再处理。');const blockRows=Object.values(this.state.pending).filter(p=>this.groupKey(p)===ref||((p.recordWritten||p.done)&&this.state.links[this.groupKey(p)]?.path===link.path));const block=makeBlock(blockRows);const planned=replaceBlock(text,block);const current=await this.host.task(link.path);if(!current)throw new SyncProblem('missing','任务笔记未找到，请重新关联。');const desired=historical?current.status:targetStatus(latest,this.settings);if(!desired)throw new SyncProblem('mapping','请配置打卡对应的任务状态。');const isLatest=!historical&&latest.revision===latest.current_revision;
 if(isLatest&&current.status!==desired&&current.status!==link.status&&current.status!==link.pendingStatus&&link.conflictChoice!=='server'){
  if(!link.conflict){const result=await this.server.conflict(latest,current.status);link.conflict=result.id;await this.host.save();}
  // Preserve records/photos before asking how to resolve the task state.
  if(planned!==text){const bodyHash=await sha(parts(planned).body.trim());const receipt=await this.server.receipt(latest,`records:${latest.instance_id}:${latest.revision}:${bodyHash.slice(0,16)}`,current.status,current.status,link.path,bodyHash);await this.host.process(link.path,value=>{if(value!==text)throw new SyncProblem('block','笔记刚被修改，请重新同步。');return planned});await this.server.ack(receipt.id,current.status,link.path,await sha(parts(await this.host.read(link.path)).body.trim()));for(const p of rows)p.recordWritten=true;link.blockHash=await sha(block);await this.host.save();}
  throw new SyncProblem('status','本地与服务器状态都有变化，请选择保留哪一方。');
 }
 if(isLatest){const oldHash=await sha(parts(text).body.trim());if(link.receiptRevision!==latest.revision){link.receiptRevision=latest.revision;link.receiptBase=current.status;}link.pendingStatus=desired;link.pendingBody=await sha(parts(planned).body.trim());await this.host.save();const statusReceipt=await this.server.receipt(latest,`status:${latest.instance_id}:${latest.revision}:${oldHash.slice(0,16)}`,desired,link.receiptBase??current.status,link.path,oldHash);if(current.status!==desired)await this.host.setStatus(link.path,desired);const verified=await this.host.task(link.path);if(verified?.status!==desired)throw new SyncProblem('status','任务状态还未更新，请稍后重试。');await this.server.ack(statusReceipt.id,desired,link.path,oldHash);
 const bodyReceipt=await this.server.receipt(latest,`body:${latest.instance_id}:${latest.revision}:${link.pendingBody.slice(0,16)}`,desired,link.receiptBase??current.status,link.path,link.pendingBody);
 const afterStatus=await this.host.read(link.path);if(parts(afterStatus).body!==parts(text).body)throw new SyncProblem('block','笔记内容刚被修改，请重新同步。');if(planned!==text)await this.host.process(link.path,value=>{if(value!==afterStatus)throw new SyncProblem('block','笔记刚被修改，请重新同步。');return replaceBlock(value,block)});
 const readBack=await this.host.read(link.path);await this.server.ack(bodyReceipt.id,desired,link.path,await sha(parts(readBack).body.trim()));link.status=desired;link.revision=latest.revision;link.pendingStatus=undefined;link.pendingBody=undefined;link.conflict=undefined;link.conflictChoice=undefined;
 }else if(planned!==text){await this.host.process(link.path,value=>{if(value!==text)throw new SyncProblem('block','笔记刚被修改，请重新同步。');return planned});}
 for(const p of rows){p.recordWritten=true;p.statusVerified=isLatest;}const blockHash=await sha(block);for(const l of Object.values(this.state.links))if(l.path===link.path)l.blockHash=blockHash;await this.host.save();
 }
 async choose(ref:string,keep:'server'|'local'):Promise<void>{const link=this.state.links[ref];const rows=Object.values(this.state.pending).filter(p=>p.item.source.source_ref===ref);const latest=rows.sort((a,b)=>b.item.cursor-a.item.cursor)[0]?.item;if(!link?.conflict||!latest)throw new SyncProblem('conflict','冲突已变化，请重新同步。');const local=await this.host.task(link.path);if(!local)throw new SyncProblem('missing','任务笔记未找到，请重新关联。');const status=this.settings.pacaStates[local.status];if(keep==='local'&&!status)throw new SyncProblem('mapping','请配置当前本地状态对应的 Paca 状态。');await this.server.resolve(link.conflict,latest,keep,status);link.conflictChoice=keep;link.status=local.status;link.conflict=undefined;for(const p of rows)p.done=false;await this.host.save();for(const p of rows){if(this.state.deliveries?.[p.item.record_id]&&this.server.action)await this.action(p.item.record_id,'retry');}await this.run();}
}
