import {sharedTaskTags} from './task-tags';
import {Plugin,PluginSettingTab,Setting,Notice,requestUrl,TFile,normalizePath,FuzzySuggestModal,Modal,type App} from 'obsidian';
import {type Host,type Task,type Settings,type State,defaults,emptyState,SyncProblem} from './types';
import {SyncEngine} from './engine';
import {PacaServer} from './server';
import {TaskSyncEngine,taskDiff} from './task-sync-engine';
import {TaskServer} from './task-sync-server';
import {tasknotes as api,taskHost,mutationContext,type TaskEvent} from './tasknotes-host';
import {emptyTaskState,type TaskSyncState,type TaskSnapshot} from './task-sync-types';
import {DeviceStore} from './device-store';
import {connectPairing,pairingCode} from './pairing';
import {serviceOrigin} from './task-sync-server';
export default class CheckinSync extends Plugin {
 settings:Settings={...defaults};state:State=emptyState();taskState:TaskSyncState=emptyTaskState();taskEngine!:TaskSyncEngine;engine!:SyncEngine;status='尚未同步';private bar!:HTMLElement;private automatic=0;private active:Promise<void>|null=null;private captures:Promise<void>=Promise.resolve();private deviceStore!:DeviceStore;private hooked=false;
 async onload():Promise<void>{
  const stored=await this.loadData() as {settings?:Partial<Settings>;state?:State}|null;this.settings={...defaults,...stored?.settings};this.state=stored?.state??emptyState();
  const key='paca-task-sync:device:'+this.app.vault.getName();let device=window.localStorage.getItem(key);if(!device){device=crypto.randomUUID();window.localStorage.setItem(key,device)}this.settings.deviceID=device;
  this.deviceStore=new DeviceStore(this.app.vault.adapter,this.manifest.dir??this.app.vault.configDir+'/plugins/'+this.manifest.id,device);const saved=await this.deviceStore.load();if(saved){this.state=saved.state;this.taskState={...emptyTaskState(),...saved.tasks}}this.resetEngine();this.bar=this.addStatusBarItem();this.bar.setText('Paca：尚未同步');
  this.addCommand({id:'sync-checkin-records',name:'同步任务、打卡记录和照片',callback:()=>void this.sync(true)});
  this.addCommand({id:'submit-current-task',name:'提交当前任务更改',callback:()=>void this.submitCurrent()});
  this.addCommand({id:'connect-existing-tasks',name:'选择已有任务接入 Paca',callback:()=>void this.connectExisting()});
  this.addSettingTab(new SyncSettings(this.app,this));this.app.workspace.onLayoutReady(()=>{this.hookTaskEvents();if(this.settings.auto&&this.settings.address&&pairingCode(this.settings))void this.sync(false)});
  this.registerDomEvent(document,'visibilitychange',()=>{if(document.visibilityState==='visible'&&this.settings.auto)void this.sync(false)});this.registerDomEvent(window,'focus',()=>{if(this.settings.auto)void this.sync(false)});
  this.registerEvent(this.app.vault.on('rename',(file,oldPath)=>{if(!(file instanceof TFile))return;for(const link of [...Object.values(this.state.links),...Object.values(this.taskState.links)])if(link.path===oldPath)link.path=file.path;void this.persist();}));this.setAutomatic();
 }
 onunload():void{window.clearInterval(this.automatic)}
 resetEngine():void{const host:Host={task:path=>api(this.app).tasks.get(path),tasks:()=>api(this.app).tasks.list(),taskFolder:()=>api(this.app).settings.snapshot().tasksFolder,read:async path=>this.app.vault.read(this.file(path)),process:async(path,transform)=>{await this.app.vault.process(this.file(path),transform)},setStatus:async(path,status)=>{await api(this.app).tasks.setStatus(path,status,mutationContext())},exists:path=>this.app.vault.getAbstractFileByPath(path)!==null,binary:async path=>this.app.vault.readBinary(this.file(path)),writeBinary:async(path,data)=>{await this.app.vault.createBinary(path,data)},mkdir:async path=>{let parent='';for(const part of normalizePath(path).split('/')){parent=parent?parent+'/'+part:part;if(!this.app.vault.getAbstractFileByPath(parent))await this.app.vault.createFolder(parent)}},save:()=>this.persist()};this.engine=new SyncEngine(host,new PacaServer(this.settings),this.settings,this.state);this.taskEngine=new TaskSyncEngine(taskHost(this.app,()=>this.persist(),(_id,link)=>{if(link.sourceRef)this.state.links[link.sourceRef]={...this.state.links[link.sourceRef],path:link.path,created:link.created,status:String(link.base.status??''),revision:link.revision}} ,()=>this.taskState.links),new TaskServer(this.settings),this.taskState);}
 file(path:string):TFile{const file=this.app.vault.getAbstractFileByPath(path);if(!(file instanceof TFile))throw new SyncProblem('missing','笔记或照片未找到，请重新关联或下载。');return file;}
 async persist():Promise<void>{await this.deviceStore.save({state:this.state,tasks:this.taskState});await this.saveData({settings:{...this.settings,deviceID:''}})}
 setAutomatic():void{window.clearInterval(this.automatic);if(this.settings.auto)this.automatic=window.setInterval(()=>void this.sync(false),Math.max(1,this.settings.minutes)*60000)}
 async sync(manual:boolean):Promise<void>{if(this.active)return this.active;this.active=this.performSync(manual).finally(()=>{this.active=null});return this.active;}
 private async performSync(manual:boolean):Promise<void>{if(!manual&&(!this.settings.address||!pairingCode(this.settings)))return;try{this.hookTaskEvents();this.status='正在同步';this.bar?.setText('Paca：正在同步');await this.captures;await connectPairing(this.settings,async(path,token,body)=>{const response=await requestUrl({url:serviceOrigin(this.settings.address)+path,method:body===undefined?'GET':'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),'X-Sync-Device':this.settings.deviceID,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),throw:false});return {status:response.status,json:response.json}});await this.persist();let taskError='';if(this.settings.taskSync){try{await this.taskEngine.run()}catch(error){taskError=error instanceof SyncProblem?error.userMessage:'任务暂未同步';}}if(this.settings.checkinSync)await this.engine.run();const needs=Object.values(this.state.pending).filter(p=>!p.done&&(this.state.deliveries?.[p.item.record_id]?this.state.deliveries[p.item.record_id].policy==='active'&&this.state.deliveries[p.item.record_id].state==='needs_action':!!p.problem&&!['unavailable','transfer_unavailable','photo'].includes(p.errorCode??''))).length+Object.keys(this.taskState.problems).length+Object.values(this.taskState.operations).filter(p=>p.state==='conflict'||p.state==='failed').length;const retry=Object.values(this.state.deliveries??{}).filter(d=>d.policy==='active'&&d.state==='retry_wait').length;this.status=needs?`${needs} 项需要处理`:taskError|| (retry?`${retry} 项等待重试`:'同步完成');if(manual)new Notice(this.status);}catch(error){this.status=error instanceof SyncProblem?error.userMessage:'暂时无法同步，请检查网络后重试。';if(manual)new Notice(this.status);}finally{this.bar?.setText('Paca：'+this.status)}}
 private hookTaskEvents():void{if(this.hooked)return;let runtime;try{runtime=api(this.app)}catch{return}this.hooked=true;const refs=['task.created','task.updated','task.deleted'].map(event=>runtime.events.on(event,payload=>this.captureEvent(payload)));this.register(()=>{for(const ref of refs)runtime.events.off(ref)});}
 private captureEvent(event:TaskEvent):void{if(!this.settings.taskSync||event.source==='paca-task-sync'||event.context?.source==='paca-task-sync')return;if(event.event==='task.updated'&&!event.before)return;this.captures=this.captures.catch(()=>{}).then(async()=>{const changes={...event.changes};if(changes.details&&typeof event.after?.details!=='string')delete changes.details;if(changes.tags){const settings=api(this.app).settings.snapshot();changes.tags={before:sharedTaskTags(changes.tags.before,settings),after:sharedTaskTags(changes.tags.after,settings)}}const kind=event.event==='task.created'?'create':event.event==='task.deleted'?'delete':'update';await this.taskEngine.capture(kind,event.before??event.deletedTask,event.after??event.task,changes)}).catch(()=>{new Notice('任务操作暂未保存，请保留笔记并手动提交当前任务更改。')});}
 async chooseTask(id:string,keep:'local'|'server'):Promise<void>{try{await this.taskEngine.choose(id,keep);await this.sync(true)}catch(e){new Notice(e instanceof SyncProblem?e.userMessage:'暂时无法处理，请重新同步。')}}
 private async submitCurrent():Promise<void>{try{const file=this.app.workspace.getActiveFile();if(!file)throw new SyncProblem('task','请先打开任务笔记。');const task=await api(this.app).tasks.get(file.path);if(!task)throw new SyncProblem('task','当前笔记不是 TaskNotes 任务。');const id=Object.keys(this.taskState.links).find(key=>this.taskState.links[key].path===task.path);if(!id)throw new SyncProblem('task','请先将此任务接入 Paca。');const host=taskHost(this.app,()=>this.persist(),()=>{},()=>this.taskState.links);const link=this.taskState.links[id];const changes=taskDiff(link.base,await host.snapshot(task));if(!Object.keys(changes).length){new Notice('当前任务没有需要提交的字段。');return}new ConfirmTaskChanges(this.app,changes,async()=>{const explicit=Object.fromEntries(Object.entries(changes).map(([key,value])=>[key,{before:link.base[key as keyof TaskSnapshot],after:value}]));await this.taskEngine.capture('update',{...task,...link.base},task,explicit);await this.sync(true)}).open()}catch(e){new Notice(e instanceof SyncProblem?e.userMessage:'无法读取当前任务。')}}
 private async connectExisting():Promise<void>{if(!this.settings.taskSync){new Notice('请先启用双向任务同步。');return}new ExistingTasks(this.app,(await api(this.app).tasks.list()).filter(t=>!Object.values(this.taskState.links).some(l=>l.path===t.path)),async tasks=>{for(const task of tasks)await this.taskEngine.capture('create',undefined,task);await this.sync(true)}).open();}
}
class NotePicker extends FuzzySuggestModal<Task>{constructor(app:App,private tasks:Task[],private picked:(task:Task)=>void){super(app);this.setPlaceholder('选择对应的任务笔记')}getItems():Task[]{return this.tasks}getItemText(task:Task):string{return task.title+' · '+task.path}onChooseItem(task:Task):void{this.picked(task)}}
const fieldLabels:Record<string,string>={title:'任务标题',details:'任务内容',scheduled:'开始时间',due:'结束时间',status:'任务状态',priority:'优先级',tags:'标签',archived:'归档',recurrence:'循环规则',recurrence_anchor:'循环锚定',complete_instances:'完成的周期',skipped_instances:'跳过的周期',recurrence_parent:'循环母任务',occurrence_date:'本期日期'};
class ConfirmTaskChanges extends Modal{constructor(app:App,private changes:TaskSnapshot,private action:()=>Promise<void>){super(app)}onOpen():void{this.contentEl.createEl('h3',{text:'提交当前任务更改'});this.contentEl.createEl('p',{text:'仅提交下列字段。打卡记录、照片引用及未映射的笔记属性保持原样。'});for(const [key,value] of Object.entries(this.changes))new Setting(this.contentEl).setName(fieldLabels[key]??'任务字段').setDesc(value===null?'清除':typeof value==='string'?value:JSON.stringify(value));new Setting(this.contentEl).addButton(b=>b.setButtonText('确认提交').setCta().onClick(()=>{this.close();void this.action()}))}onClose():void{this.contentEl.empty()}}
class ExistingTasks extends Modal{constructor(app:App,private tasks:Task[],private action:(tasks:Task[])=>Promise<void>){super(app)}onOpen():void{const selected=new Set<Task>();this.contentEl.createEl('h3',{text:'选择已有任务接入 Paca'});this.contentEl.createEl('p',{text:'只导入勾选的任务；同名任务不会自动合并。'});for(const task of this.tasks)new Setting(this.contentEl).setName(task.title).setDesc(task.path).addToggle(t=>t.onChange(value=>{if(value)selected.add(task);else selected.delete(task)}));new Setting(this.contentEl).addButton(b=>b.setButtonText('接入所选任务').setCta().onClick(()=>{if(!selected.size){new Notice('请先选择任务。');return}this.close();void this.action([...selected])}))}onClose():void{this.contentEl.empty()}}
class ConfirmBlock extends Modal{constructor(app:App,private action:()=>Promise<void>){super(app)}onOpen():void{this.contentEl.createEl('h3',{text:'恢复打卡区块'});this.contentEl.createEl('p',{text:'打卡区块将按服务器记录重新生成，区块以外的正文保持不变。请先保存区块内需要保留的修改。'});new Setting(this.contentEl).addButton(b=>b.setButtonText('恢复并同步').setWarning().onClick(()=>{this.close();void this.action()}));}onClose():void{this.contentEl.empty()}}
class ConfirmIgnore extends Modal{constructor(app:App,private action:()=>Promise<void>){super(app)}onOpen():void{this.contentEl.createEl('h3',{text:'忽略此同步项'});this.contentEl.createEl('p',{text:'同一笔记库的设备都会停止重试此记录。任务、打卡记录和照片保留，可随时恢复同步。'});new Setting(this.contentEl).addButton(b=>b.setButtonText('取消').onClick(()=>this.close())).addButton(b=>b.setButtonText('确认忽略').setWarning().onClick(()=>{this.close();void this.action()}))}onClose():void{this.contentEl.empty()}}
class SyncSettings extends PluginSettingTab {
 private pacaStatuses:{id:string;name:string}[]=[];
 constructor(app:App,private p:CheckinSync){super(app,p)}
 display():void{const {containerEl:c}=this;c.empty();c.addClass('paca-sync-settings');c.createEl('h2',{text:'Paca 任务同步'});c.createEl('h3',{text:'连接'});const save=async()=>{await this.p.persist();this.p.resetEngine();this.p.setAutomatic()};
 new Setting(c).setName('Paca 服务地址').addText(t=>t.setPlaceholder('https://example.com').setValue(this.p.settings.address).onChange(async v=>{this.p.settings.address=v.trim();await save()}));
 new Setting(c).setName('配对码').setDesc('在 Paca 中生成。同一笔记库的电脑和手机可使用同一个配对码。').addText(t=>{t.inputEl.type='password';t.setValue(pairingCode(this.p.settings)).onChange(async v=>{this.p.settings.pairingCode=v.trim();this.p.settings.pairingMode=undefined;delete this.p.settings.token;delete this.p.settings.taskToken;await save()})}).addExtraButton(b=>b.setIcon('copy').setTooltip('复制配对码').onClick(()=>{void navigator.clipboard.writeText(pairingCode(this.p.settings)).then(()=>new Notice('配对码已复制'))}));
 c.createEl('h3',{text:'同步'});
 new Setting(c).setName('双向任务同步').setDesc('同步任务的创建、修改、状态及删除。').addToggle(t=>t.setValue(this.p.settings.taskSync).onChange(async v=>{this.p.settings.taskSync=v;await save()}));
 new Setting(c).setName('打卡记录和照片').setDesc('与普通任务同步分别控制。').addToggle(t=>t.setValue(this.p.settings.checkinSync).onChange(async v=>{this.p.settings.checkinSync=v;await save()}));
 c.createEl('h3',{text:'附件与状态'});
 new Setting(c).setName('照片附件目录').setDesc('独立存放照片，不能与任务目录相同或位于其中。').addText(t=>t.setValue(this.p.settings.attachments).onChange(async v=>{this.p.settings.attachments=v;await save()}));
 let states:{value:string;label:string}[]=[];try{states=api(this.app).catalog.statuses()}catch{c.createEl('p',{text:'请先启用官方 TaskNotes 插件。'})}
 for(const [key,label] of [['started','开始打卡后状态'],['completed','结束打卡后状态']] as const)new Setting(c).setName(label).addDropdown(d=>{d.addOption('','请选择任务状态');for(const s of states)d.addOption(s.value,s.label);d.setValue(this.p.settings[key]).onChange(async v=>{this.p.settings[key]=v;await save()})});
 new Setting(c).setName('自动同步').setDesc('启动、回到前台及定时拉取。').addToggle(t=>t.setValue(this.p.settings.auto).onChange(async v=>{this.p.settings.auto=v;await save()}));new Setting(c).setName('同步间隔（分钟）').addText(t=>{t.inputEl.type='number';t.setValue(String(this.p.settings.minutes)).onChange(async v=>{this.p.settings.minutes=Math.max(1,Number(v)||5);await save()})});
 new Setting(c).setName('同步状态').setDesc(this.p.status).addButton(b=>b.setButtonText('同步任务、打卡记录和照片').setCta().onClick(async()=>{b.setDisabled(true);await this.p.sync(true);this.display()}));
 for(const [id,message] of Object.entries(this.p.taskState.problems)){const item=this.p.taskState.pending[id];const link=this.p.taskState.links[id];const panel=c.createDiv({cls:'paca-sync-card'});panel.createEl('h3',{text:String(item?.snapshot.title??'任务同步')});panel.createEl('p',{text:message});if(link&&message.includes('冲突'))new Setting(panel).setName('任务冲突').addButton(b=>b.setButtonText('采用服务器内容').onClick(async()=>{await this.p.chooseTask(id,'server');this.display()})).addButton(b=>b.setButtonText('采用本地内容').onClick(async()=>{await this.p.chooseTask(id,'local');this.display()}));new Setting(panel).setName('关联笔记').addButton(b=>b.setButtonText('选择笔记').onClick(async()=>{new NotePicker(this.app,await api(this.app).tasks.list(),task=>{if(!item)return;this.p.taskState.links[id]={path:task.path,created:task.dateCreated??'',base:item.snapshot,revision:0,sourceRef:item.source_ref};void this.p.persist().then(()=>this.p.sync(true)).then(()=>this.display())}).open()}));}
 for(const row of Object.values(this.p.taskState.operations).filter(v=>v.state==='conflict'||v.state==='failed')){const panel=c.createDiv({cls:'paca-sync-card'});panel.createEl('h3',{text:String(row.body.changes.title??this.p.taskState.links[row.body.sync_id]?.base.title??'待提交任务')});panel.createEl('p',{text:row.problem??'需要核对任务操作。'});if(row.state==='conflict')new Setting(panel).setName('任务冲突').addButton(b=>b.setButtonText('采用服务器内容').onClick(async()=>{await this.p.chooseTask(row.body.sync_id,'server');this.display()})).addButton(b=>b.setButtonText('采用本地内容').onClick(async()=>{await this.p.chooseTask(row.body.sync_id,'local');this.display()}));}
 new Setting(c).setName('本地状态与 Paca 状态对应').setDesc('处理“采用本地状态”的冲突时使用。').addButton(b=>b.setButtonText('加载项目状态').onClick(async()=>{try{this.pacaStatuses=(await new PacaServer(this.p.settings).info()).statuses;this.display()}catch{new Notice('暂时无法加载，请检查服务地址与配对码。')}}));for(const state of states)new Setting(c).setName(state.label).addDropdown(d=>{d.addOption('','请选择 Paca 状态');for(const ps of this.pacaStatuses)d.addOption(ps.id,({'Todo':'待完成','In Progress':'进行中','Done':'已完成','Backlog':'待安排','Archive':'已归档'} as Record<string,string>)[ps.name]??ps.name);d.setValue(this.p.settings.pacaStates[state.value]??'').onChange(async v=>{this.p.settings.pacaStates[state.value]=v;await save()})});
 c.createEl('h3',{text:'打卡同步记录'});let showHistory=false;const history=c.createDiv();const render=()=>{history.empty();for(const row of Object.values(this.p.state.pending)){const d=this.p.state.deliveries?.[row.item.record_id];const hidden=d&&d.policy!=='active';if((hidden&&!showHistory)||(row.done&&!hidden))continue;const ref=row.item.source.source_ref,link=this.p.state.links[d?.historical_path?ref+'|historical:'+d.historical_path+'|'+d.historical_created:ref];const panel=history.createDiv({cls:'paca-sync-card'});panel.createEl('h4',{text:row.item.source.snapshot.title||'任务打卡'});panel.createEl('p',{text:(row.item.kind==='start'?'开始打卡':'结束打卡')+' · '+new Date(row.item.submitted_at).toLocaleString()});panel.createEl('p',{text:hidden?(d.policy==='ignored'?'已忽略':'任务已删除，记录已归档'):d?.state==='retry_wait'?'等待自动重试':d?.state==='needs_action'?(row.problem||(d.error_code==='source_missing'?'任务来源需要关联，请重新关联或忽略此同步项。':'需要处理，请重试或核对记录。')):row.problem||'等待同步'});panel.createEl('p',{text:'照片：'+(row.photo?'已保存':row.expired?'已过期':'待下载')+' · 记录：'+(row.recordWritten?'已写入':'待写入')});
 const run=async(action:'retry'|'ignore'|'restore'|'associate',task?:Task)=>{try{await this.p.engine.action(row.item.record_id,action,task);this.display()}catch(e){new Notice(e instanceof SyncProblem?e.userMessage:'处理暂未完成，请重新同步。')}};
 if(hidden){new Setting(panel).addButton(b=>b.setButtonText('恢复同步').onClick(()=>void run('restore')));continue;}
 new Setting(panel).addButton(b=>b.setButtonText('重试同步').onClick(()=>void run('retry'))).addButton(b=>b.setButtonText('忽略此同步项').onClick(()=>{new ConfirmIgnore(this.app,()=>run('ignore')).open()}));
 if(link?.conflict)new Setting(panel).setName('状态冲突').addButton(b=>b.setButtonText('采用服务器状态').onClick(()=>void this.choose(ref,'server'))).addButton(b=>b.setButtonText('采用本地状态').onClick(()=>void this.choose(ref,'local')));
 new Setting(panel).setName('重新关联笔记').addButton(b=>b.setButtonText('选择笔记').onClick(async()=>{new NotePicker(this.app,await api(this.app).tasks.list(),task=>{void run('associate',task)}).open()}));if(row.errorCode==='block')new Setting(panel).setName('打卡区块').addButton(b=>b.setButtonText('恢复区块').onClick(()=>{new ConfirmBlock(this.app,async()=>{if(link)link.blockHash=undefined;await this.p.persist();await run('retry')}).open()}));}};new Setting(c).setName('显示已忽略及已归档记录').addToggle(t=>t.onChange(value=>{showHistory=value;render()}));render();

 }
 private async choose(ref:string,keep:'server'|'local'):Promise<void>{try{await this.p.engine.choose(ref,keep);this.display()}catch(e){new Notice(e instanceof SyncProblem?e.userMessage:'暂时无法处理，请重新同步。')}}
}
