import {Plugin,PluginSettingTab,Setting,Notice,TFile,normalizePath,FuzzySuggestModal,Modal,type App} from 'obsidian';
import {type Host,type Task,type Settings,type State,defaults,emptyState,SyncProblem} from './types';
import {SyncEngine} from './engine';
import {PacaServer} from './server';
interface TaskNotesApi {apiVersion:string;tasks:{get(path:string):Promise<Task|null>;list():Promise<Task[]>;setStatus(path:string,status:string,context?:{source:string;operationId:string}):Promise<unknown>};catalog:{statuses():{value:string;label:string}[]};settings:{snapshot():{tasksFolder:string}}}
interface PluginRegistry {plugins:Record<string,{api?:TaskNotesApi}>}
function api(app:App):TaskNotesApi{const runtime=(app as App&{plugins:PluginRegistry}).plugins.plugins.tasknotes?.api;if(!runtime||!runtime.tasks?.setStatus)throw new SyncProblem('tasknotes','请启用官方 TaskNotes 插件后再同步。');return runtime;}
export default class CheckinSync extends Plugin {
 settings:Settings={...defaults};state:State=emptyState();engine!:SyncEngine;status='尚未同步';private bar!:HTMLElement;private automatic=0;private active:Promise<void>|null=null;
 async onload():Promise<void>{const stored=await this.loadData() as {settings?:Partial<Settings>;state?:State}|null;this.settings={...defaults,...stored?.settings};this.state=stored?.state??emptyState();this.resetEngine();this.bar=this.addStatusBarItem();this.bar.setText('打卡：尚未同步');this.addCommand({id:'sync-checkin-records',name:'同步打卡记录、状态和照片',callback:()=>void this.sync(true)});this.addSettingTab(new SyncSettings(this.app,this));this.app.workspace.onLayoutReady(()=>{if(this.settings.auto&&this.settings.address&&this.settings.token)void this.sync(false)});this.registerDomEvent(document,'visibilitychange',()=>{if(document.visibilityState==='visible'&&this.settings.auto)void this.sync(false)});this.registerDomEvent(window,'focus',()=>{if(this.settings.auto)void this.sync(false)});this.registerEvent(this.app.vault.on('rename',(file,oldPath)=>{if(!(file instanceof TFile))return;for(const link of Object.values(this.state.links))if(link.path===oldPath)link.path=file.path;void this.persist();}));this.setAutomatic();}
 onunload():void{window.clearInterval(this.automatic)}
 resetEngine():void{const host:Host={task:path=>api(this.app).tasks.get(path),tasks:()=>api(this.app).tasks.list(),taskFolder:()=>api(this.app).settings.snapshot().tasksFolder,read:async path=>this.app.vault.read(this.file(path)),process:async(path,transform)=>{await this.app.vault.process(this.file(path),transform)},setStatus:async(path,status)=>{await api(this.app).tasks.setStatus(path,status,{source:'paca-checkin-sync',operationId:crypto.randomUUID()})},exists:path=>this.app.vault.getAbstractFileByPath(path)!==null,binary:async path=>this.app.vault.readBinary(this.file(path)),writeBinary:async(path,data)=>{await this.app.vault.createBinary(path,data)},mkdir:async path=>{let parent='';for(const part of normalizePath(path).split('/')){parent=parent?parent+'/'+part:part;if(!this.app.vault.getAbstractFileByPath(parent))await this.app.vault.createFolder(parent)}},save:()=>this.persist()};this.engine=new SyncEngine(host,new PacaServer(this.settings),this.settings,this.state);}
 file(path:string):TFile{const file=this.app.vault.getAbstractFileByPath(path);if(!(file instanceof TFile))throw new SyncProblem('missing','笔记或照片未找到，请重新关联或下载。');return file;}
 persist():Promise<void>{return this.saveData({settings:this.settings,state:this.state})}
 setAutomatic():void{window.clearInterval(this.automatic);if(this.settings.auto)this.automatic=window.setInterval(()=>void this.sync(false),Math.max(1,this.settings.minutes)*60000)}
 async sync(manual:boolean):Promise<void>{if(this.active)return this.active;this.active=this.performSync(manual).finally(()=>{this.active=null});return this.active;}
 private async performSync(manual:boolean):Promise<void>{if(!manual&&(!this.settings.address||!this.settings.token))return;try{this.status='正在同步';this.bar?.setText('打卡：正在同步');await this.engine.run();const pending=Object.values(this.state.pending).filter(p=>!p.done);this.status=pending.length?`${pending.length} 条记录需要处理`:'同步完成';if(manual)new Notice(this.status);}catch(error){this.status=error instanceof SyncProblem?error.userMessage:'暂时无法同步，请检查网络后重试。';if(manual)new Notice(this.status);}finally{this.bar?.setText('打卡：'+this.status)}}
}
class NotePicker extends FuzzySuggestModal<Task>{constructor(app:App,private tasks:Task[],private picked:(task:Task)=>void){super(app);this.setPlaceholder('选择对应的任务笔记')}getItems():Task[]{return this.tasks}getItemText(task:Task):string{return task.title+' · '+task.path}onChooseItem(task:Task):void{this.picked(task)}}
class ConfirmBlock extends Modal{constructor(app:App,private action:()=>Promise<void>){super(app)}onOpen():void{this.contentEl.createEl('h3',{text:'恢复打卡区块'});this.contentEl.createEl('p',{text:'打卡区块将按服务器记录重新生成，区块以外的正文保持不变。请先保存区块内需要保留的修改。'});new Setting(this.contentEl).addButton(b=>b.setButtonText('恢复并同步').setWarning().onClick(()=>{this.close();void this.action()}));}onClose():void{this.contentEl.empty()}}
class SyncSettings extends PluginSettingTab {
 private pacaStatuses:{id:string;name:string}[]=[];
 constructor(app:App,private p:CheckinSync){super(app,p)}
 display():void{const {containerEl:c}=this;c.empty();c.addClass('paca-sync-settings');c.createEl('h2',{text:'Paca 打卡同步'});c.createEl('p',{text:'将打卡状态、记录和照片同步到当前笔记库。'});const save=async()=>{await this.p.persist();this.p.resetEngine();this.p.setAutomatic()};
 new Setting(c).setName('打卡服务地址').setDesc('例如 https://task.spacedo.org').addText(t=>t.setPlaceholder('https://task.spacedo.org').setValue(this.p.settings.address).onChange(async v=>{this.p.settings.address=v.trim();await save()}));new Setting(c).setName('设备配对码').setDesc('在 Paca 打卡设置中为当前设备生成。').addText(t=>{t.inputEl.type='password';t.setValue(this.p.settings.token).onChange(async v=>{this.p.settings.token=v.trim();await save()})});new Setting(c).setName('照片附件目录').setDesc('独立存放照片，不能与任务目录相同或位于其中。').addText(t=>t.setValue(this.p.settings.attachments).onChange(async v=>{this.p.settings.attachments=v;await save()}));
 let states:{value:string;label:string}[]=[];try{states=api(this.app).catalog.statuses()}catch{c.createEl('p',{text:'请先启用官方 TaskNotes 插件。'})}
 for(const [key,label] of [['started','开始打卡后状态'],['completed','结束打卡后状态']] as const)new Setting(c).setName(label).addDropdown(d=>{d.addOption('','请选择任务状态');for(const s of states)d.addOption(s.value,s.label);d.setValue(this.p.settings[key]).onChange(async v=>{this.p.settings[key]=v;await save()})});
 new Setting(c).setName('自动同步').setDesc('启动、回到前台及定时拉取。').addToggle(t=>t.setValue(this.p.settings.auto).onChange(async v=>{this.p.settings.auto=v;await save()}));new Setting(c).setName('同步间隔（分钟）').addText(t=>{t.inputEl.type='number';t.setValue(String(this.p.settings.minutes)).onChange(async v=>{this.p.settings.minutes=Math.max(1,Number(v)||5);await save()})});
 new Setting(c).setName('同步状态').setDesc(this.p.status).addButton(b=>b.setButtonText('同步打卡记录、状态和照片').setCta().onClick(async()=>{b.setDisabled(true);await this.p.sync(true);this.display()}));
 new Setting(c).setName('本地状态与 Paca 状态对应').setDesc('处理“采用本地状态”的冲突时使用。').addButton(b=>b.setButtonText('加载项目状态').onClick(async()=>{try{this.pacaStatuses=(await new PacaServer(this.p.settings).info()).statuses;this.display()}catch{new Notice('暂时无法加载，请检查服务地址与配对码。')}}));for(const state of states)new Setting(c).setName(state.label).addDropdown(d=>{d.addOption('','请选择 Paca 状态');for(const ps of this.pacaStatuses)d.addOption(ps.id,({'Todo':'待完成','In Progress':'进行中','Done':'已完成','Backlog':'待安排','Archive':'已归档'} as Record<string,string>)[ps.name]??ps.name);d.setValue(this.p.settings.pacaStates[state.value]??'').onChange(async v=>{this.p.settings.pacaStates[state.value]=v;await save()})});
 const refs=new Set(Object.values(this.p.state.pending).filter(row=>!row.done).map(row=>row.item.source.source_ref));for(const ref of refs){const row=Object.values(this.p.state.pending).find(row=>row.item.source.source_ref===ref);if(!row)continue;const link=this.p.state.links[ref];const panel=c.createDiv({cls:'paca-sync-card'});panel.createEl('h3',{text:row.item.source.snapshot.title||'任务打卡'});panel.createEl('p',{text:row.problem||'等待同步'});if(link?.conflict){new Setting(panel).setName('状态冲突').addButton(b=>b.setButtonText('采用服务器状态').onClick(()=>void this.choose(ref,'server'))).addButton(b=>b.setButtonText('采用本地状态').onClick(()=>void this.choose(ref,'local')));}new Setting(panel).setName('关联任务笔记').addButton(b=>b.setButtonText('选择笔记').onClick(async()=>{new NotePicker(this.app,await api(this.app).tasks.list(),task=>{this.p.state.links[ref]={path:task.path,created:task.dateCreated,status:task.status,revision:0};void this.p.persist().then(()=>this.p.sync(true)).then(()=>this.display())}).open()}));if(row.problem?.includes('区块'))new Setting(panel).setName('打卡区块').addButton(b=>b.setButtonText('恢复区块').onClick(()=>{new ConfirmBlock(this.app,async()=>{if(link)link.blockHash=undefined;await this.p.persist();await this.p.sync(true);this.display()}).open()}));}
 }
 private async choose(ref:string,keep:'server'|'local'):Promise<void>{try{await this.p.engine.choose(ref,keep);this.display()}catch(e){new Notice(e instanceof SyncProblem?e.userMessage:'暂时无法处理，请重新同步。')}}
}
