import {requestUrl} from 'obsidian';
import {type Server,type Settings,type Checkin,type Source,SyncProblem} from './types';
export class PacaServer implements Server {
 constructor(readonly settings:Settings){}
 private base():string {let url:URL;try{url=new URL(this.settings.address)}catch{throw new SyncProblem('address','请填写有效的 Paca 服务地址。')}if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash||url.pathname.replace(/\/$/,'')!=='')throw new SyncProblem('address','请填写不带路径的 HTTPS 服务地址。');if(this.settings.taskToken)return url.origin+'/task-sync/v1/checkin';if(!/^[a-f0-9]{64}$/.test(this.settings.token))throw new SyncProblem('token','请填写有效的设备配对码。');return url.origin+'/checkin-api/v1/sync';}
 private async request(path:string,body?:unknown,binary=false):Promise<unknown|ArrayBuffer>{const response=await requestUrl({url:this.base()+path,method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+(this.settings.taskToken||this.settings.token),'X-Sync-Device':this.settings.deviceID,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),throw:false});if(response.status===410)throw new SyncProblem('expired','照片已超过保存期限。');if(response.status===401||response.status===403)throw new SyncProblem('token','设备授权已失效，请重新配对。');if(response.status===404)throw new SyncProblem('missing','来源关联未找到，请检查任务是否已删除。');if(response.status===409)throw new SyncProblem('revision','任务已更新，请重新同步后处理。');if(response.status!==200&&response.status!==201)throw new SyncProblem('unavailable','暂时无法连接服务，请稍后重试。');return binary?response.arrayBuffer:response.json;}
 async changes(after:number):Promise<{items:Checkin[];next_cursor:number;has_more:boolean}>{return await this.request('/changes?after='+after) as {items:Checkin[];next_cursor:number;has_more:boolean}}
 async source(task:string):Promise<Source>{return await this.request('/sources/'+encodeURIComponent(task)) as Source}
 async media(id:string):Promise<ArrayBuffer>{return await this.request('/media/'+encodeURIComponent(id),undefined,true) as ArrayBuffer}
 async receipt(item:Checkin,op:string,status:string,base:string,path:string,hash:string):Promise<{id:string}>{return await this.request('/receipts',{cursor:item.cursor,op_id:op,status,base_status:base,path,base_revision:item.revision,details_sha256:hash}) as {id:string}}
 async ack(id:string,status:string,path:string,hash:string):Promise<void>{await this.request('/receipts/'+id+'/ack',{status,path,details_sha256:hash})}
 async conflict(item:Checkin,local:string):Promise<{id:string}>{return await this.request('/conflicts',{instance_id:item.instance_id,base_revision:item.revision,local:{status:local}}) as {id:string}}
 async resolve(id:string,item:Checkin,keep:'server'|'local',status?:string):Promise<void>{await this.request('/conflicts/'+id+'/resolve',{keep,base_revision:item.revision,...(status?{paca_status_id:status}:{})})}
 async info():Promise<{statuses:{id:string;name:string}[];connection_id:string}>{return await this.request('/info') as {statuses:{id:string;name:string}[];connection_id:string}}
}
