export const taskFields=['title','details','scheduled','due','status','priority','tags','archived','recurrence','recurrence_anchor','complete_instances','skipped_instances','recurrence_parent','occurrence_date'] as const;
export type TaskSnapshot=Partial<Record<typeof taskFields[number],unknown>>;
export interface TaskChange{cursor:number;sync_id:string;task_id:string;revision:number;kind:'task'|'series'|'occurrence';deleted:boolean;path:string;note_created:string;source_ref:string;snapshot:TaskSnapshot;warnings?:string[]}
export interface TaskLink{path:string;created:string;revision:number;base:TaskSnapshot;sourceRef:string;intent?:boolean;receipt?:string;receiptOp?:string;receiptRevision?:number;receiptExpected?:TaskSnapshot;receiptFields?:string[];problem?:string;deleted?:boolean}
export interface TaskOperation{op_id:string;sync_id:string;base_revision:number;kind:'create'|'update'|'delete';base:TaskSnapshot;changes:TaskSnapshot;path?:string;note_created?:string}
export interface LocalOperation{body:TaskOperation;state:'queued'|'pending'|'conflict'|'failed';problem?:string}
export interface TaskSyncState{cursor:number;links:Record<string,TaskLink>;pending:Record<string,TaskChange>;operations:Record<string,LocalOperation>;problems:Record<string,string>}
export const emptyTaskState=():TaskSyncState=>({cursor:0,links:{},pending:{},operations:{},problems:{}});
export interface SyncedTask{path:string;dateCreated?:string;[key:string]:unknown}
export interface TaskSyncHost{task(path:string):Promise<SyncedTask|null>;find(syncID:string):Promise<SyncedTask|null>;create(snapshot:TaskSnapshot,syncID:string):Promise<SyncedTask>;update(path:string,patch:TaskSnapshot,syncID:string):Promise<SyncedTask>;delete(path:string):Promise<void>;snapshot(task:SyncedTask):Promise<TaskSnapshot>;save():Promise<void>;bound(id:string,link:TaskLink):void}
export interface TaskSyncServer{info():Promise<{mode:string}>;changes(cursor:number):Promise<{items:TaskChange[];next_cursor:number;has_more:boolean;mode:string}>;binding(id:string,action:'claim'|'confirm',path?:string,created?:string):Promise<{state:string;path?:string;note_created?:string}>;submit(operation:TaskOperation):Promise<{state:string}>;operation(id:string):Promise<{state:string;error?:string;result?:{sync_id?:string}}> ;receipt(item:TaskChange,op:string,fields:string[]):Promise<{id:string}>;ack(id:string,snapshot:TaskSnapshot,path:string,created:string):Promise<void>;lookup(path:string,created:string):Promise<{sync_id:string;revision:number;snapshot:TaskSnapshot}>;conflicts():Promise<{items:TaskConflict[]}>;resolve(id:string,keep:'local'|'server',revision:number):Promise<void>}
export interface TaskConflict{id:string;sync_id:string;base_revision:number;base:TaskSnapshot;local:TaskSnapshot;remote:TaskSnapshot;fields:string[]}
