export interface Task {path:string;title:string;status:string;dateCreated?:string;archived?:boolean;[key:string]:unknown}
export interface Source {source_ref:string;connection_id:string;path:string;aliases?:string[];source_state?:'active'|'deleted'|'unlinked';snapshot:{status:string;dateCreated?:string;title?:string}}
export interface Checkin {cursor:number;record_id:string;instance_id:string;task_id:string;revision:number;current_revision:number;logical_status:string;paca_status_id:string;kind:'start'|'due';submitted_at:string;note:string;media_id:string;media_sha256:string;media_bytes:number;media_mime:string;media_expired:boolean;source:Source}
export interface Settings {address:string;pairingCode?:string;pairingMode?:'task'|'checkin';token?:string;taskToken?:string;deviceID:string;taskSync:boolean;checkinSync:boolean;auto:boolean;minutes:number;attachments:string;started:string;completed:string;pacaStates:Record<string,string>}
export const defaults:Settings={address:'',pairingCode:'',deviceID:'',taskSync:false,checkinSync:true,auto:true,minutes:5,attachments:'PushGo附件',started:'in-progress',completed:'done',pacaStates:{}};
export interface Pending {item:Checkin;photo?:string;expired?:boolean;done?:boolean;problem?:string;conflict?:string;errorCode?:string;recordWritten?:boolean;statusVerified?:boolean;report?:DeliveryReport}
export interface Delivery {record_id:string;policy:'active'|'ignored'|'archived_deleted'|'purging'|'purged';revision:number;reason:string;historical_path:string;historical_created:string;state:'pending'|'retry_wait'|'needs_action'|'confirmed';attempts:number;next_attempt?:string;error_code:string;media_verified:boolean;record_written:boolean;status_verified:boolean}
export interface DeliveryReport {record_id:string;op_id:string;base_revision:number;stage:'progress'|'failed'|'confirmed';error_code:string;media_sha256:string;media_verified:boolean;record_written:boolean;status_verified:boolean}
export interface DeliveryAction {connection_id:string;record_id:string;op_id:string;action:'retry'|'ignore'|'restore'|'associate'|'purge';base_revision:number;path?:string;note_created?:string}
export interface Link {path:string;created?:string;status:string;revision:number;blockHash?:string;pendingStatus?:string;pendingBody?:string;receiptBase?:string;receiptRevision?:number;conflict?:string;conflictChoice?:'server'|'local'}
export interface State {cursor:number;pending:Record<string,Pending>;links:Record<string,Link>;media:Record<string,{path:string;sha:string}>;deliveryCursor?:number;deliveries?:Record<string,Delivery>}
export const emptyState=():State=>({cursor:0,pending:{},links:{},media:{},deliveryCursor:0,deliveries:{}});
export interface Host {task(path:string):Promise<Task|null>;tasks():Promise<Task[]>;taskFolder():string;read(path:string):Promise<string>;process(path:string,transform:(text:string)=>string):Promise<void>;setStatus(path:string,status:string):Promise<void>;exists(path:string):boolean;binary(path:string):Promise<ArrayBuffer>;writeBinary(path:string,data:ArrayBuffer):Promise<void>;mkdir(path:string):Promise<void>;save():Promise<void>}
export interface Server {changes(after:number):Promise<{items:Checkin[];next_cursor:number;has_more:boolean}>;source(task:string):Promise<Source>;media(id:string):Promise<ArrayBuffer>;receipt(item:Checkin,op:string,status:string,base:string,path:string,hash:string):Promise<{id:string}>;ack(id:string,status:string,path:string,hash:string):Promise<void>;conflict(item:Checkin,local:string):Promise<{id:string}>;resolve(id:string,item:Checkin,keep:'server'|'local',status?:string):Promise<void>;deliveries?(after:number):Promise<{items:Delivery[];next_cursor:number;has_more:boolean}>;report?(body:DeliveryReport):Promise<Partial<Delivery>>;action?(body:DeliveryAction):Promise<unknown>}
export class SyncProblem extends Error {constructor(public code:string,public userMessage:string){super(userMessage)}}
